// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import HelloController from "./hello_controller"


import { application } from "./application"
import { sidebar } from "./sidebar"


application.register("hello", HelloController)
sidebar();
